-- ==============================================================================
-- НАУЧНЫЙ ПРОЕКТ DEBATR — СХЕМА БАЗЫ ДАННЫХ SUPABASE (PostgreSQL)
-- Разработчик: Ихлас Мұстафа (10 «А» класс)
-- Инструкция: Откройте Supabase Dashboard -> SQL Editor -> New Query -> Вставьте и нажмите RUN
-- ==============================================================================

-- 1. Таблица speeches (История речей, баттлов с GPT-6 Luna и аналитики)
CREATE TABLE IF NOT EXISTS public.speeches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    student_name TEXT NOT NULL,
    exercise_type TEXT NOT NULL DEFAULT 'battle', -- 'battle', '1v1', 'speech'
    topic TEXT NOT NULL,
    content TEXT,
    overall_score NUMERIC(3, 1),
    scores JSONB DEFAULT '{}'::jsonb, -- structure, evidence, rebuttal, clarity, originality
    status TEXT DEFAULT 'confirmed'
);

-- 2. Таблица profiles (Профили пользователей, синхронизированные с Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE,
    display_name TEXT,
    school TEXT DEFAULT 'Школа-лицей №13',
    level TEXT DEFAULT 'novice',
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Таблица rooms (Комнаты дружеских матчей 1 на 1)
CREATE TABLE IF NOT EXISTS public.rooms (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code TEXT UNIQUE NOT NULL,
    topic TEXT NOT NULL,
    status TEXT DEFAULT 'waiting', -- 'waiting', 'active', 'finished'
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Таблица room_matches (Результаты дуэлей в комнатах 1 на 1)
CREATE TABLE IF NOT EXISTS public.room_matches (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    room_code TEXT NOT NULL REFERENCES public.rooms(code) ON DELETE CASCADE,
    p1_name TEXT NOT NULL,
    p1_speech TEXT,
    p2_name TEXT NOT NULL,
    p2_speech TEXT,
    winner TEXT,
    scores JSONB DEFAULT '{}'::jsonb,
    feedback TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- ИНДЕКСЫ ДЛЯ ПРОИЗВОДИТЕЛЬНОСТИ
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_speeches_created_at ON public.speeches(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_speeches_student ON public.speeches(student_name);
CREATE INDEX IF NOT EXISTS idx_rooms_code ON public.rooms(code);
CREATE INDEX IF NOT EXISTS idx_room_matches_code ON public.room_matches(room_code);

-- ==============================================================================
-- НАСТРОЙКА ROW LEVEL SECURITY (RLS)
-- Политики настроены для беспрепятственной работы школьного веб-приложения
-- ==============================================================================
ALTER TABLE public.speeches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_matches ENABLE ROW LEVEL SECURITY;

-- Удаление старых политик при повторном перезапуске скрипта
DROP POLICY IF EXISTS "Allow public read access on speeches" ON public.speeches;
DROP POLICY IF EXISTS "Allow public insert on speeches" ON public.speeches;
DROP POLICY IF EXISTS "Allow public read profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow all on profiles" ON public.profiles;
DROP POLICY IF EXISTS "Allow public read rooms" ON public.rooms;
DROP POLICY IF EXISTS "Allow all on rooms" ON public.rooms;
DROP POLICY IF EXISTS "Allow public read room_matches" ON public.room_matches;
DROP POLICY IF EXISTS "Allow all on room_matches" ON public.room_matches;

-- Политики для speeches
CREATE POLICY "Allow public read access on speeches" 
    ON public.speeches FOR SELECT USING (true);

CREATE POLICY "Allow public insert on speeches" 
    ON public.speeches FOR INSERT WITH CHECK (true);

-- Политики для profiles
CREATE POLICY "Allow public read profiles" 
    ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Allow all on profiles" 
    ON public.profiles FOR ALL USING (true) WITH CHECK (true);

-- Политики для rooms
CREATE POLICY "Allow public read rooms" 
    ON public.rooms FOR SELECT USING (true);

CREATE POLICY "Allow all on rooms" 
    ON public.rooms FOR ALL USING (true) WITH CHECK (true);

-- Политики для room_matches
CREATE POLICY "Allow public read room_matches" 
    ON public.room_matches FOR SELECT USING (true);

CREATE POLICY "Allow all on room_matches" 
    ON public.room_matches FOR ALL USING (true) WITH CHECK (true);
